.Dd January 14 2025
.Dt gimura 7
.Os
.
.Sh NAME
.Nm gimura2022.github.io
.Nd gimura2022 personal site
.
.Sh DESCRIPTION
Hi! I'm gimura (or gimura2022).
How you can see I C developer uses linux (but my utilities usualy work on other UNIX systems).
.
.Ss Articles
.Bl -tag -width Ds
.It some article
.Lk https://github.com/gimura2022 github
.It some article 2
.Lk https://github.com/gimura2022 github
.El
.
.Sh CONTACTS
.Lk https://github.com/gimura2022 github
.Pp
.An gimura2022 Aq Mt gimura0001@gmail.com
